/**
 * IMAGE POSE ANALYSIS
 * ===================
 * Single-image pose detection via MediaPipe; match to 150 pose clusters from
 * Tsolak & Kühne (2025). Shows gender-associated pattern (masculine/feminine/neutral).
 */

import {
    BONES,
    findClosestCluster,
    getTopMatches,
    getGenderColor,
    drawMiniSkeleton,
    getHowItWorksHTML
} from './pose-utils.js';

// -----------------------------------------------------------------------------
// GLOBAL STATE
// -----------------------------------------------------------------------------

let POSE_CLUSTERS = null;      // Loaded from pose_clusters.json
let mediapipePose = null;      // MediaPipe Pose instance
let mediapipeReady = false;
let pendingCallback = null;   // One-shot callback for async pose detection
let matchK = 5;               // Number of nearest clusters to blend (1–5)

const $ = id => document.getElementById(id);

// -----------------------------------------------------------------------------
// DATA LOADING
// -----------------------------------------------------------------------------

/** Load 150 pose clusters from JSON (generated by cluster_poses.py) */
async function loadData() {
    try {
        const res = await fetch('data/pose_clusters.json');
        if (res.ok) POSE_CLUSTERS = await res.json();
    } catch (err) {
        console.error('Error loading pose clusters:', err);
    }
}

// -----------------------------------------------------------------------------
// DRAWING
// -----------------------------------------------------------------------------

/** Draw image + skeleton overlay on canvas (green bones, red joints) */
function drawSkeleton(ctx, kp, img) {
    ctx.clearRect(0, 0, ctx.canvas.width, ctx.canvas.height);
    if (img) {
        const scale = Math.min(ctx.canvas.width / img.width, ctx.canvas.height / img.height);
        const w = img.width * scale, h = img.height * scale;
        ctx.drawImage(img, (ctx.canvas.width - w) / 2, (ctx.canvas.height - h) / 2, w, h);
    }
    if (!kp) return;
    ctx.strokeStyle = '#00ff88';
    ctx.lineWidth = 5;
    ctx.lineCap = 'round';
    for (const [start, end] of BONES) {
        if (kp[start] && kp[end]) {
            ctx.beginPath();
            ctx.moveTo(kp[start].x, kp[start].y);
            ctx.lineTo(kp[end].x, kp[end].y);
            ctx.stroke();
        }
    }
    for (const name in kp) {
        const pt = kp[name];
        if (!pt?.x) continue;
        ctx.beginPath();
        ctx.arc(pt.x, pt.y, 7, 0, Math.PI * 2);
        ctx.fillStyle = '#ff0000';
        ctx.fill();
        ctx.strokeStyle = '#ffffff';
        ctx.lineWidth = 2;
        ctx.stroke();
    }
}

// -----------------------------------------------------------------------------
// UI UPDATES
// -----------------------------------------------------------------------------

/** Render pattern panel: match result, k selector, top matched clusters */
function updatePatternPanel(keypoints) {
    const container = $('patternContent');
    if (!container) return;
    if (!keypoints) {
        container.innerHTML = '<p class="placeholder-text">Upload an image to see pattern analysis</p>';
        return;
    }
    const clusters = POSE_CLUSTERS?.clusters;
    const match = findClosestCluster(clusters, keypoints, matchK);
    const topMatches = getTopMatches(clusters, keypoints, matchK);
    if (!match) {
        container.innerHTML = '<p class="placeholder-text">No pose match</p>';
        return;
    }
    const kTitle = matchK === 1 ? 'Best match (k=1)' : `Weighted blend (k=${matchK})`;
    const kExplanation = matchK === 1
        ? 'Single closest cluster. Uses cluster character from multinomial test (paper-aligned).'
        : `Blended from ${matchK} nearest clusters. Closer = more influence.`;
    const label = match.character === 'masculine' ? 'Masculine-associated' : match.character === 'feminine' ? 'Feminine-associated' : 'Neutral';
    const malePct = match.malePercent.toFixed(0);
    const femalePct = match.femalePercent.toFixed(0);
    container.innerHTML = `
        <div class="k-selector-row">
            <label>Matching method:</label>
            <select id="matchKSelect">
                <option value="1" ${matchK === 1 ? 'selected' : ''}>k=1 (best match)</option>
                <option value="2" ${matchK === 2 ? 'selected' : ''}>k=2</option>
                <option value="3" ${matchK === 3 ? 'selected' : ''}>k=3</option>
                <option value="4" ${matchK === 4 ? 'selected' : ''}>k=4</option>
                <option value="5" ${matchK === 5 ? 'selected' : ''}>k=5</option>
            </select>
        </div>
        <div class="match-sections">
            <div class="match-section">
                <h4 class="match-section-title">${kTitle}</h4>
                <div class="result-label">${label}</div>
                <div class="result-bars">
                    <div class="result-bar"><span>Male</span> <span>${malePct}%</span></div>
                    <div class="bar-track"><div class="bar-segment male" style="width:${malePct}%"></div><div class="bar-segment female" style="width:${femalePct}%"></div></div>
                    <div class="result-bar"><span>Female</span> <span>${femalePct}%</span></div>
                </div>
                <p class="result-explanation">${kExplanation}</p>
            </div>
        </div>
        <div class="matched-categories">
            <h4>Top ${matchK} matched categories:</h4>
            <div class="match-grid">
                ${topMatches.map((m, i) => `
                    <div class="match-card">
                        <canvas id="matchCanvas${i}" width="60" height="75"></canvas>
                        <div class="match-info">
                            <span>#${m.cluster.id}</span>
                            <span class="match-sim">${m.similarity}% similar</span>
                            <span class="match-stats">${m.cluster.malePercent.toFixed(0)}%M / ${m.cluster.femalePercent.toFixed(0)}%F</span>
                        </div>
                    </div>
                `).join('')}
            </div>
        </div>
    `;
    $('matchKSelect').onchange = () => {
        matchK = parseInt($('matchKSelect').value, 10);
        updatePatternPanel(keypoints);
    };
    setTimeout(() => {
        topMatches.forEach((m, i) => {
            const canvas = $(`matchCanvas${i}`);
            if (canvas && m.cluster.prototype) {
                drawMiniSkeleton(canvas, m.cluster.prototype, getGenderColor(m.cluster));
            }
        });
    }, 10);
}

/** Show "How it works" static content */
function updateMatchingClusters() {
    const container = $('matchingClusters');
    if (!container) return;
    container.innerHTML = getHowItWorksHTML();
}

// -----------------------------------------------------------------------------
// MEDIAPIPE
// -----------------------------------------------------------------------------

/** Route MediaPipe results to the current pending callback */
function handlePoseResults(results) {
    if (pendingCallback) {
        const cb = pendingCallback;
        pendingCallback = null;
        cb(results);
    }
}

/** MediaPipe landmarks → canvas pixel coords; derive neck and midhip from shoulders/hips */
/** MediaPipe landmarks → canvas pixel coords; derive neck and midhip from shoulders/hips */
function convertLandmarks(landmarks, canvasW, canvasH, imgW, imgH) {
    const scale = Math.min(canvasW / imgW, canvasH / imgH);
    const w = imgW * scale, h = imgH * scale;
    const offsetX = (canvasW - w) / 2, offsetY = (canvasH - h) / 2;
    const map = {
        nose: 0, lshoulder: 11, rshoulder: 12, lelbow: 13, relbow: 14,
        lwrist: 15, rwrist: 16, lhip: 23, rhip: 24, lknee: 25, rknee: 26,
        lankle: 27, rankle: 28, bigtoe: 31, rbigtoe: 32
    };
    const MIN_VISIBILITY = 0.5;
    const kp = {};
    for (const name in map) {
        const lm = landmarks[map[name]];
        if (lm && (lm.visibility ?? 1) >= MIN_VISIBILITY) kp[name] = { x: lm.x * w + offsetX, y: lm.y * h + offsetY };
    }
    if (kp.lshoulder && kp.rshoulder) {
        kp.neck = { x: (kp.lshoulder.x + kp.rshoulder.x) / 2, y: (kp.lshoulder.y + kp.rshoulder.y) / 2 };
    }
    if (kp.lhip && kp.rhip) {
        kp.midhip = { x: (kp.lhip.x + kp.rhip.x) / 2, y: (kp.lhip.y + kp.rhip.y) / 2 };
    }
    return kp;
}

/** Initialize MediaPipe Pose (warm-up with test image) */
/** Initialize MediaPipe Pose (warm-up with test image) */
async function initMediaPipe() {
    return new Promise((resolve) => {
        mediapipePose = new Pose({
            locateFile: file => `https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.5.1675469404/${file}`
        });
        mediapipePose.setOptions({
            modelComplexity: 1,
            smoothLandmarks: true,
            minDetectionConfidence: 0.5,
            minTrackingConfidence: 0.5
        });
        mediapipePose.onResults(handlePoseResults);
        const testCanvas = document.createElement('canvas');
        testCanvas.width = 100;
        testCanvas.height = 100;
        testCanvas.getContext('2d').fillRect(0, 0, 100, 100);
        pendingCallback = () => { mediapipeReady = true; resolve(); };
        mediapipePose.send({ image: testCanvas }).catch(() => { mediapipeReady = true; resolve(); });
        setTimeout(() => { if (!mediapipeReady) { mediapipeReady = true; resolve(); } }, 8000);
    });
}

// -----------------------------------------------------------------------------
// IMAGE PROCESSING
// -----------------------------------------------------------------------------

/** Detect pose in image, draw skeleton, update pattern panel */
async function processImage(img) {
    pendingCallback = null;
    if (!mediapipeReady) await initMediaPipe();
    return new Promise((resolve) => {
        const timeout = setTimeout(() => { pendingCallback = null; resolve(null); }, 10000);
        pendingCallback = (results) => {
            clearTimeout(timeout);
            if (!results.poseLandmarks) { resolve(null); return; }
            const canvas = $('previewCanvas');
            const kp = convertLandmarks(results.poseLandmarks, canvas.width, canvas.height, img.width, img.height);
            drawSkeleton(canvas.getContext('2d'), kp, img);
            updatePatternPanel(kp);
            updateMatchingClusters();
            resolve(kp);
        };
        mediapipePose.send({ image: img }).catch(() => {
            clearTimeout(timeout);
            pendingCallback = null;
            resolve(null);
        });
    });
}

// -----------------------------------------------------------------------------
// INIT
// -----------------------------------------------------------------------------

document.addEventListener('DOMContentLoaded', async () => {
    await loadData();
    await initMediaPipe();
    updateMatchingClusters();
    $('uploadBtn').onclick = () => $('imageInput').click();
    $('imageInput').onchange = (e) => {
        const file = e.target.files[0];
        if (!file) return;
        $('uploadPlaceholder').style.display = 'none';
        $('previewArea').style.display = 'flex';
        $('clearBtn').style.display = 'inline-block';
        const img = new Image();
        img.onload = async () => {
            const canvas = $('previewCanvas');
            const ctx = canvas.getContext('2d');
            ctx.clearRect(0, 0, canvas.width, canvas.height);
            const scale = Math.min(canvas.width / img.width, canvas.height / img.height);
            const w = img.width * scale, h = img.height * scale;
            ctx.drawImage(img, (canvas.width - w) / 2, (canvas.height - h) / 2, w, h);
            await processImage(img);
        };
        img.src = URL.createObjectURL(file);
    };
    $('clearBtn').onclick = () => {
        pendingCallback = null;
        const canvas = $('previewCanvas');
        if (canvas) canvas.getContext('2d')?.clearRect(0, 0, canvas.width, canvas.height);
        $('uploadPlaceholder').style.display = 'flex';
        $('previewArea').style.display = 'none';
        $('clearBtn').style.display = 'none';
        $('imageInput').value = '';
        updatePatternPanel(null);
        updateMatchingClusters();
    };
});
